# Generated by Django 5.1.6 on 2025-02-23 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_seller'),
        ('shops', '0003_delete_sellerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='shops.shop'),
        ),
    ]
