# Generated by Django 5.1.6 on 2025-03-02 10:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('shops', '0004_businessperiodconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancesheet',
            old_name='total_credit',
            new_name='net_profit',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='total_paid',
            new_name='total_expenses',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='total_sales',
            new_name='total_revenue',
        ),
        migrations.AlterUniqueTogether(
            name='balancesheet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='cash_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='credit_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='partial_payments',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
        migrations.CreateModel(
            name='CreditSalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_credit_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_pending_payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
            options={
                'unique_together': {('date', 'shop')},
            },
        ),
        migrations.CreateModel(
            name='DamagedStockReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_damaged_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_damaged_items', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
            options={
                'unique_together': {('date', 'shop')},
            },
        ),
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
            options={
                'unique_together': {('date', 'shop')},
            },
        ),
        migrations.CreateModel(
            name='StockReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_stock_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_items_in_stock', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
            options={
                'unique_together': {('date', 'shop')},
            },
        ),
        migrations.CreateModel(
            name='SupplierReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('supplier_name', models.CharField(max_length=255)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('date', 'supplier_name')},
            },
        ),
        migrations.DeleteModel(
            name='AccountingReport',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='shop',
        ),
    ]
