# Generated by Django 5.1.6 on 2025-03-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_total_credit_balancesheet_net_profit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BalanceSheet',
        ),
        migrations.AlterUniqueTogether(
            name='creditsalesreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='creditsalesreport',
            name='shop',
        ),
        migrations.AlterUniqueTogether(
            name='damagedstockreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='damagedstockreport',
            name='shop',
        ),
        migrations.AlterUniqueTogether(
            name='expensereport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='expensereport',
            name='shop',
        ),
        migrations.AlterUniqueTogether(
            name='productperformancereport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productperformancereport',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productperformancereport',
            name='shop',
        ),
        migrations.AlterUniqueTogether(
            name='profitreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='profitreport',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='profitreport',
            name='shop',
        ),
        migrations.AlterUniqueTogether(
            name='salesreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='salesreport',
            name='shop',
        ),
        migrations.AlterUniqueTogether(
            name='stockreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockreport',
            name='shop',
        ),
        migrations.DeleteModel(
            name='SupplierReport',
        ),
        migrations.DeleteModel(
            name='CreditSalesReport',
        ),
        migrations.DeleteModel(
            name='DamagedStockReport',
        ),
        migrations.DeleteModel(
            name='ExpenseReport',
        ),
        migrations.DeleteModel(
            name='ProductPerformanceReport',
        ),
        migrations.DeleteModel(
            name='ProfitReport',
        ),
        migrations.DeleteModel(
            name='SalesReport',
        ),
        migrations.DeleteModel(
            name='StockReport',
        ),
    ]
