# Generated by Django 5.1.6 on 2025-02-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_remove_shop_created_by_alter_shop_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerProfile',
        ),
    ]
