# Generated by Django 5.1.6 on 2025-02-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_creditsale_sale_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='quantity',
            new_name='stock_quantity',
        ),
    ]
