# Generated by Django 5.1.6 on 2025-02-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_sale_options_remove_sale_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='date',
            new_name='sale_date',
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
