# Generated by Django 5.1.6 on 2025-02-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_rename_price_per_piece_saleitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
