# Generated by Django 5.1.6 on 2025-02-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_saleitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
