# Generated by Django 5.1.6 on 2025-03-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_damagedgoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='period_processed',
            field=models.BooleanField(default=False),
        ),
    ]
