# Generated by Django 5.1.6 on 2025-03-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_sale_status_cashtransaction_credittransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagedgoods',
            name='total_loss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
